### ISSUE TITLE
[BUG] IndexError in track_package()

### ISSUE THREAD

**Issue by nehaljwani** [marcelotrevisani/grayskull#178]
```
$ grayskull pypi pyinstaller-hooks-contrib

#### Initializing recipe for pyinstaller-hooks-contrib (pypi) ####

...

Matching license file with database from Grayskull...
License type: GPL-2.0
License file: LICENSE.GPL.txt
Traceback (most recent call last):
  File "/home/wani/m3/envs/grayskull/bin/grayskull", line 10, in <module>
    sys.exit(main())
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/__main__.py", line 121, in main
    recipe = GrayskullFactory.create_recipe(
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/base/factory.py", line 22, in create_recipe
    return GrayskullFactory.REGISTERED_CLASS[repo_type.lower()](
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 58, in __init__
    super(PyPi, self).__init__(name=name, version=str(version) if version else None)
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/base/base_recipe.py", line 58, in __init__
    self.update_all_recipe()
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/base/base_recipe.py", line 112, in update_all_recipe
    self.refresh_section(section)
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 522, in refresh_section
    metadata = self._get_metadata()
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/pypi/pypi.py", line 564, in _get_metadata
    all_requirements["host"] = solve_list_pkg_name(
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/base/track_packages.py", line 38, in solve_list_pkg_name
    return [re_norm.sub(",", solve_pkg_name(pkg, config_file)) for pkg in list_pkg]
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/base/track_packages.py", line 38, in <listcomp>
    return [re_norm.sub(",", solve_pkg_name(pkg, config_file)) for pkg in list_pkg]
  File "/home/wani/m3/envs/grayskull/lib/python3.8/site-packages/grayskull/base/track_packages.py", line 43, in solve_pkg_name
    config_pkg = track_package(pkg_name_sep[0], config_file)
IndexError: list index out of range
```

**Comment by marcelotrevisani** [comment]
Hi @nehaljwani ,
Thanks for reporting this bug and opening a PR to fix it! I really appreciate it!
I just did a comment there, I hope you don't mind.
After that I believe we can integrate it and I will cut a new release for grayskull.

**Comment by marcelotrevisani** [comment]
I generated version ``0.8.1`` with your fix! Thanks a lot!
