### ISSUE TITLE
Import fails using Python 3.8.5

### ISSUE THREAD

**Issue by dmyersturnbull** [marcelotrevisani/grayskull#184]
**Describe the bug**

**To Reproduce**
1. Install Miniconda on Windows 10 as of 2020-08-28.
2. Run:
   ```bash
    conda create --name fresh \
   --override-channels --channel conda-forge \
    --force --yes python=3.8
    pip install tox poetry grayskull
    ```
2. Run `conda activate fresh && grayskull --version`

**Outputs**

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Miniconda3\lib\site-packages\grayskull\base\factory.py", line 4, in <module>
    from grayskull.pypi import PyPi
  File "C:\ProgramData\Miniconda3\lib\site-packages\grayskull\pypi\__init__.py", line 1, in <module>
    from grayskull.pypi.pypi import PyPi  # noqa
  File "C:\ProgramData\Miniconda3\lib\site-packages\grayskull\pypi\pypi.py", line 21, in <module>
    from grayskull.base.base_recipe import AbstractRecipeModel
  File "C:\ProgramData\Miniconda3\lib\site-packages\grayskull\base\base_recipe.py", line 11, in <module>
    from ruamel.yaml import YAML, CommentToken
ImportError: cannot import name 'YAML' from 'ruamel.yaml' (unknown location)
```

**Environment:**
 - conda list:
  ```
# Name                    Version                   Build  Channel
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
openssl                   1.1.1g               he774522_1    conda-forge
pip                       20.2.2                     py_0    conda-forge
python                    3.8.5           h60c2a47_7_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
setuptools                49.6.0           py38h32f6830_0    conda-forge
sqlite                    3.33.0               he774522_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2                   py38_1003    conda-forge
  ```
 - pip list: a bit redundant
 - grayskull --version: **fails**

**Comment by dmyersturnbull** [comment]
Also tried:

```bash
pip uninstall grayskull
pip install grayskull=0.7.4
```

Same issue.

**Comment by dmyersturnbull** [comment]
This fixed it:

```
install ruamel.yaml==0.16.10
Collecting ruamel.yaml==0.16.10
  Using cached ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Processing c:\users\douglas\appdata\local\pip\cache\wheels\e4\3e\eb\975034325f52bc0d5897b5f8603974d6a79a964aaeb0ec0293\ruamel.yaml.clib-0.2.0-cp38-cp38-win_amd64.whl
Installing collected packages: ruamel.yaml.clib, ruamel.yaml
  Attempting uninstall: ruamel.yaml
    Found existing installation: ruamel-yaml 0.15.87
ERROR: Cannot uninstall 'ruamel-yaml'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
(fresh) PS C:\Users\douglas\Desktop\code\tyrannosaurus> pip install ruamel.yaml==0.16.10 --force
```

Then:

```
pip install ruamel.yaml==0.16.10 --force --ignore-installed
Collecting ruamel.yaml==0.16.10
  Using cached ruamel.yaml-0.16.10-py2.py3-none-any.whl (111 kB)
Processing c:\users\douglas\appdata\local\pip\cache\wheels\e4\3e\eb\975034325f52bc0d5897b5f8603974d6a79a964aaeb0ec0293\ruamel.yaml.clib-0.2.0-cp38-cp38-win_amd64.whl
Installing collected packages: ruamel.yaml.clib, ruamel.yaml
Successfully installed ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0
(fresh) PS C:\Users\douglas\Desktop\code\tyrannosaurus> grayskull --version
0.8.1
```

However, it may be good to replace `"ruamel.yaml >=0.15.3"` in `setup.py` with `"ruamel.yaml >=0.16.10"`.
(Oddly, `pip install ruamel.yaml==0.16.0 --force --ignore-installed` installs 0.16.10. Maybe there isn't a 0.16.0.)

**Comment by marcelotrevisani** [comment]
Thanks for reporting it, I was not aware about this problem
I believe I didn't see that on the CI because it was using the latest version of the ruamel.
